name: Main

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    needs: [lint]
    secrets: inherit
